package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Locator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/centos/8/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Monday, April 22, 2024 9:31:03 AM UTC
*/

public interface Locator extends LocatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Locator
