package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/centos/8/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, April 22, 2024 9:31:05 AM UTC
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
  	 * The value representing REQUEST_PROCESSING_POLICY_ID.
  	 */
  public static final int value = (int)(22L);
}
