package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/INACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/centos/8/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, April 22, 2024 9:31:05 AM UTC
*/

public interface INACTIVE
{

  /** Object adapter state that causes all requests to be discarded.
     * This state indicates that the adapter is shutting down.
     */
  public static final short value = (short)(3);
}
